package org.example.util;

import org.example.enums.Position;
import org.example.model.CardInput;
import org.example.model.CardScore;
import org.example.model.Manager;
import org.example.model.PlayerCard;
import org.example.model.Tactic;
import org.example.model.Team;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.example.enums.Position.CAM;
import static org.example.enums.Position.CB;
import static org.example.enums.Position.CDM;
import static org.example.enums.Position.CF;
import static org.example.enums.Position.CM;
import static org.example.enums.Position.GK;
import static org.example.enums.Position.LB;
import static org.example.enums.Position.LM;
import static org.example.enums.Position.LW;
import static org.example.enums.Position.LWB;
import static org.example.enums.Position.RB;
import static org.example.enums.Position.RM;
import static org.example.enums.Position.RW;
import static org.example.enums.Position.RWB;
import static org.example.enums.Position.ST;

public class InputData {

    protected static final List<CardInput> playerCardInputList = new ArrayList<>();
    protected static final List<Tactic> tacticList = new ArrayList<>();
    protected static final List<Manager> managerList = new ArrayList<>();
    protected static final Map<Position, List<String>> positionAttributesMap = new HashMap<>();
    protected static final long startTime = System.nanoTime();
    protected static final int playersToConsider = 5;
    protected static final boolean shouldConsiderLoans = false;
    protected static final boolean shouldConsiderPlayerPositionMods = true;
    protected static final boolean shouldSaveHeapSpace = true;
    protected static final Map<Integer, PlayerCard> playerCardMap = new LinkedHashMap<>();
    protected static List<Team> possibleTeams = new ArrayList<>();
    protected static final List<String> chemStyles = List.of("hunter", "anchor", "basic", "cat", "sniper","finisher","deadeye","marksman","hawk","artist","architect","powerhouse","maestro","engine","sentinel","guardian","gladiator","backbone","catalyst","shadow","wall","glove","shield");
    protected static Map<Position, List<CardScore>> playerPositionMap = new HashMap<>();

    protected static final List<List<Integer>> cb2 = new ArrayList<>();
    protected static final List<List<Integer>> cb3 = new ArrayList<>();
    protected static final List<List<Integer>> cm2 = new ArrayList<>();
    protected static final List<List<Integer>> st2 = new ArrayList<>();
    protected static final List<List<Integer>> cf2 = new ArrayList<>();
    protected static final List<List<Integer>> cdm2 = new ArrayList<>();
    protected static final List<List<Integer>> cam2 = new ArrayList<>();
    protected static final List<List<Integer>> cm3 = new ArrayList<>();

    protected static long allTeamsCount = 1;
    protected static long teamCounter = 0;
    protected static final List<Position> duplicatePositions = List.of(CB, CM, ST, CF, CDM, CAM);

    public static String key = "";
    public static List<Integer> substituteMap = new ArrayList<>();
    protected static List<Integer> mandatoryPlayers = List.of();

    protected static List<CardInput> populateWishList() {
        List<CardInput> wishListPlayers = new ArrayList<>();
        return wishListPlayers;
    }

    protected static void populateLoans() {
        playerCardInputList.add(new CardInput(52953, "RONALDO TT", ST, 97));
        playerCardInputList.add(new CardInput(52767, "PUSKAS BIRTHDAY", CF, 95));
        playerCardInputList.add(new CardInput(54008, "SOCRATES SS", CM, 95));
        playerCardInputList.add(new CardInput(52768, "BEST BIRTHDAY", RW, 94));
        playerCardInputList.add(new CardInput(52515, "SANCHEZ FANT", CF, 94));
        playerCardInputList.add(new CardInput(52910, "BERGKAMP TT", CF, 94));
        playerCardInputList.add(new CardInput(262, "RONALDINHO", LW, 94));
        playerCardInputList.add(new CardInput(50599, "EDERMILITAO TOTY", CB, 94));
        playerCardInputList.add(new CardInput(31, "CARLOS ALBERTO", RB, 93));
        playerCardInputList.add(new CardInput(52528, "GINOLA FANT", ST, 92));
        playerCardInputList.add(new CardInput(51755, "BARELLA RTTF", CM, 92));
        playerCardInputList.add(new CardInput(51754, "GORETZKA RTTF", CM, 92));
        playerCardInputList.add(new CardInput(247, "RIVALDO", LW, 92));
        playerCardInputList.add(new CardInput(52621, "OKOCHA FANT", CAM, 91));
        playerCardInputList.add(new CardInput(52622, "KUYT FANT", CAM, 91));
        playerCardInputList.add(new CardInput(52754, "MARQUINHOS BIRTHDAY", CB, 91));
        playerCardInputList.add(new CardInput(51763, "GABRIEL MARTINELLI RTTF", LM, 91));
        playerCardInputList.add(new CardInput(51753, "FIRMINO RTTF", CF, 91));
        playerCardInputList.add(new CardInput(26264, "DE BRUYNE", CM, 91));
        playerCardInputList.add(new CardInput(50450, "KIMMICH WW", CM, 91));
        playerCardInputList.add(new CardInput(301, "ZIDANE", CM, 91));
        playerCardInputList.add(new CardInput(52519, "LLORENTE FANT", CM, 91));
        playerCardInputList.add(new CardInput(26263, "MBAPPE", ST, 91));
        playerCardInputList.add(new CardInput(26261, "BENZEMA", ST, 91));
        playerCardInputList.add(new CardInput(26265, "MESSI", RW, 91));
        playerCardInputList.add(new CardInput(50393, "KANTE WW", CDM, 91));
        playerCardInputList.add(new CardInput(51769, "LAMELA RTTF", RW, 90));
        playerCardInputList.add(new CardInput(52623, "DI NATALE FANT", ST, 90));
        playerCardInputList.add(new CardInput(50759, "CRISTIANO RONALDO", ST, 90));
        playerCardInputList.add(new CardInput(50394, "SANCHO WW", CAM, 90));
        playerCardInputList.add(new CardInput(52525, "ALLI FANT", CAM, 89));
        playerCardInputList.add(new CardInput(52625, "PARK JI SUNG FANT", CM, 89));
        playerCardInputList.add(new CardInput(52827, "EL SHAARAWY BIRTHDAY", CF, 89));
        playerCardInputList.add(new CardInput(52906, "DONOVAN TT", CF, 89));
        playerCardInputList.add(new CardInput(51758, "FOFANA RTTF", CB, 89));
        playerCardInputList.add(new CardInput(50397, "JOAO FELIX WW", RW, 89));
        playerCardInputList.add(new CardInput(26256, "XABI ALONSO", CDM, 89));
        playerCardInputList.add(new CardInput(26275, "CASEMIRO", CDM, 89));
        playerCardInputList.add(new CardInput(26280, "OBLAK", GK, 89));
        playerCardInputList.add(new CardInput(51671, "NKETIAH FS", ST, 89));
        playerCardInputList.add(new CardInput(44212, "VOLLER", ST, 89));
        playerCardInputList.add(new CardInput(52759, "EMERSON BIRTHDAY", RWB, 88));
        playerCardInputList.add(new CardInput(52613, "CAN FANT", CM, 88));
        playerCardInputList.add(new CardInput(50506, "JORDI ALBA FUTC", LB, 88));
        playerCardInputList.add(new CardInput(26307, "CANCELO", LB, 88));
        playerCardInputList.add(new CardInput(50454, "VARANE WW", CB, 88));
        playerCardInputList.add(new CardInput(50574, "THIAGO SILVA TOTW", CB, 88));
        playerCardInputList.add(new CardInput(53197, "CARTER-VICKERS TOTSM", CB, 88));
        playerCardInputList.add(new CardInput(51198, "MAVIDIDI TOTW", LM, 88));
        playerCardInputList.add(new CardInput(47266, "FORLAN", ST, 88));
        playerCardInputList.add(new CardInput(37536, "MILITO", ST, 88));
        playerCardInputList.add(new CardInput(51677, "WILLOCK FS", CM, 87));
        playerCardInputList.add(new CardInput(50437, "GRAVENBERCH WW", CM, 87));
        playerCardInputList.add(new CardInput(47289, "KEWELL", LW, 87));
        playerCardInputList.add(new CardInput(50458, "BOATENG WW", CB, 87));
        playerCardInputList.add(new CardInput(50459, "WEGHORST WW", CB, 87));
        playerCardInputList.add(new CardInput(27792, "COLE", RW, 87));
        playerCardInputList.add(new CardInput(50469, "FABIO WW", RB, 86));
        playerCardInputList.add(new CardInput(50405, "TOLJAN WW", RB, 86));
        playerCardInputList.add(new CardInput(50346, "MAC ALLISTER WCTOTT", CM, 86));
        playerCardInputList.add(new CardInput(48664, "BELLINGHAM TOTW", CM, 86));
        playerCardInputList.add(new CardInput(26381, "ALABA", CB, 86));
        playerCardInputList.add(new CardInput(50462, "ADAMA TRAORE WW", ST, 86));
        playerCardInputList.add(new CardInput(26295, "VINICIUS JR", LW, 86));
        playerCardInputList.add(new CardInput(50581, "RASHFORD TOTW", LM, 85));
        playerCardInputList.add(new CardInput(50440, "ISMAILY WW", LB, 85));
        playerCardInputList.add(new CardInput(26296, "GREALISH", LW, 84));
        playerCardInputList.add(new CardInput(26301, "VALVERDE", CM, 84));
        playerCardInputList.add(new CardInput(50411, "CHONG WW", LM, 84));
    }

    protected static void populatePlayerInput() {
        playerCardInputList.add(new CardInput(28,  "VAN DIJK" , CB, 89));
        playerCardInputList.add(new CardInput(54274,  "DONNARUMMA PREMIUM FUTTIES" , GK, 99));
        playerCardInputList.add(new CardInput(54249,  "ZIDANE CS ICON" , CAM, 99));
        playerCardInputList.add(new CardInput(54209,  "NEYMAR JR FUTTIES" , CAM, 99));
        playerCardInputList.add(new CardInput(54275,  "HAALAND PREMIUM FUTTIES" , ST, 99));
        playerCardInputList.add(new CardInput(54298,  "HENRY CS ICON" , ST, 99));
        playerCardInputList.add(new CardInput(54292,  "MATTHAUS CS ICON" , CM, 99));
        playerCardInputList.add(new CardInput(54303,  "BELLINGHAM MOMENTS" , CM, 99));
        playerCardInputList.add(new CardInput(54251,  "BENZEMA PREMIUM FUTTIES" , CF, 99));

        playerCardInputList.add(new CardInput(54259,  "ALISSON FUTTIES" , GK, 98));
        playerCardInputList.add(new CardInput(54164,  "VINICIUS JR PREMIUM FUTTIES" , LW, 98));
//        playerCardInputList.add(new CardInput(54260,  "RASHFORD FUTTIES" , LW, 98));
//        playerCardInputList.add(new CardInput(54267,  "GOVOU FUTTIES" , ST, 98));
//        playerCardInputList.add(new CardInput(54268,  "DEL PIERO CS ICON" , CF, 98));
//        playerCardInputList.add(new CardInput(54293,  "ODEGAARD PREMIUM FUTTIES" , CAM, 98));
        playerCardInputList.add(new CardInput(54284,  "ABEDI PELE FUTTIES" , CAM, 98));
//        playerCardInputList.add(new CardInput(54304,  "KIM MIN JAE MOMENTS" , CB, 98));
            playerCardInputList.add(new CardInput(54307,  "JORDI ALBA MOMENTS" , LB, 98));

        playerCardInputList.add(new CardInput(54232,  "OBLAK FUTTIES", GK, 97));
        playerCardInputList.add(new CardInput(54180,  "ROBERTO CARLOS CS ICON", LB, 97));
        playerCardInputList.add(new CardInput(54226,  "LLORENTE FUTTIES" , CM, 97));
        playerCardInputList.add(new CardInput(54252,  "FLORENZI PREMIUM FUTTIES" , CM, 97));
        playerCardInputList.add(new CardInput(53782,  "MODRIC TOTS" , CM, 97, true));
        playerCardInputList.add(new CardInput(53208,  "DE BRUYNE TOTS" , CM, 97, true));
        playerCardInputList.add(new CardInput(54311,  "ARTHUR MOMENTS" , CM, 97, true));
        playerCardInputList.add(new CardInput(54240,  "XABI ALONSO CS ICON" , CDM, 97));
        playerCardInputList.add(new CardInput(53921,  "KROOS SS" , CDM, 97));
        playerCardInputList.add(new CardInput(54279,  "SERGIO BUSQUETS PREMIUM FUTTIES" , CDM, 97));
//        playerCardInputList.add(new CardInput(54222,  "ROONEY CS ICON" , ST, 97));
        playerCardInputList.add(new CardInput(53780,  "LEWANDOWSKI TOTS" , ST, 97));
        playerCardInputList.add(new CardInput(54210,  "JESUS FUTTIES" , ST, 97));
        playerCardInputList.add(new CardInput(54067,  "POGBA SS" , ST, 97));
//        playerCardInputList.add(new CardInput(54040,  "DEMBELE SS" , CAM, 97));
        playerCardInputList.add(new CardInput(54189,  "REUS FUTTIES" , CAM, 97));
        playerCardInputList.add(new CardInput(53745,  "MUSIALA TOTS" , CAM, 97));
        playerCardInputList.add(new CardInput(54233,  "ALABA FUTTIES" , CB, 97, true));
        playerCardInputList.add(new CardInput(53869,  "RAFAEL LEAO TOTS" , LW, 97, true));
        playerCardInputList.add(new CardInput(54301,  "SANCHEZ MOMENTS" , LW, 97, true));
        playerCardInputList.add(new CardInput(53997,  "BRUNO FERNANDES SS" , LW, 97, true));

        playerCardInputList.add(new CardInput(54097,  "CALHANOGLU LU (2)" , CM, 96));
        playerCardInputList.add(new CardInput(50606,  "MODRIC TOTY" , CM, 96, true));
        playerCardInputList.add(new CardInput(53998,  "DEPAY SS" , CM, 96));
//        playerCardInputList.add(new CardInput(54068,  "LLORIS SS" , CM, 96));
        playerCardInputList.add(new CardInput(54280,  "FRED PREMIUM FUTTIES" , CM, 96, true));
        playerCardInputList.add(new CardInput(54197,  "KOULIBALY PREMIUM FUTTIES" , CB, 96));
//        playerCardInputList.add(new CardInput(54269,  "LACROIX PREMIUM FUTTIES" , CB, 96, true));
//        playerCardInputList.add(new CardInput(50600,  "VAN DIJK TOTY" , CB, 96));
        playerCardInputList.add(new CardInput(53748,  "DE LIGT TOTS" , CB, 96, true));
        playerCardInputList.add(new CardInput(54297,  "CARVALHO FUTTIES" , CB, 96, true));
        playerCardInputList.add(new CardInput(53212,  "RUBEN DIAS TOTS" , CB, 96));
        playerCardInputList.add(new CardInput(54196,  "ABRAHAM FUTTIES" , ST, 96));
//        playerCardInputList.add(new CardInput(54244,  "SHEVCHENKO CS ICON" , ST, 96));
        playerCardInputList.add(new CardInput(54163,  "DIOGO JOTA FUTTIES" , ST, 96));
//        playerCardInputList.add(new CardInput(54190,  "GRIEZMANN FUTTIES" , ST, 96));
        playerCardInputList.add(new CardInput(53999,  "RUDIGER SS" , ST, 96, true));
        playerCardInputList.add(new CardInput(54091,  "CAVANI PREMIUM LU (2)" , ST, 96));
//        playerCardInputList.add(new CardInput(54286,  "SMOLAREK FUTTIES" , ST, 96, true));
//        playerCardInputList.add(new CardInput(54302,  "ARNAUTOVIC MOMENTS" , ST, 96, true));
        playerCardInputList.add(new CardInput(53747,  "KIMMICH TOTS" , CDM, 96, true));
        playerCardInputList.add(new CardInput(54042,  "DE JONG SS" , CDM, 96));
//        playerCardInputList.add(new CardInput(54254,  "ISCO PREMIUM FUTTIES" , CAM, 96, true));
//        playerCardInputList.add(new CardInput(54241,  "RUI COSTA CS ICON" , CAM, 96));
        playerCardInputList.add(new CardInput(54006,  "VAN PERSIE SS" , CAM, 96, true));
//        playerCardInputList.add(new CardInput(54235,  "COUTINHO FUTTIES" , CAM, 96, true));
        playerCardInputList.add(new CardInput(54253,  "CHIESA PREMIUM FUTTIES" , RW, 96));
        playerCardInputList.add(new CardInput(54212,  "SANCHO FUTTIES" , RW, 96, true));
        playerCardInputList.add(new CardInput(53210,  "SALAH TOTS" , RW, 96, true));
//        playerCardInputList.add(new CardInput(54287,  "DONOVAN FUTTIES" , CF, 96, true));
        playerCardInputList.add(new CardInput(54296,  "LOVE PREMIUM FUTTIES" , RB, 96, true));
        playerCardInputList.add(new CardInput(54211,  "CARVAJAL FUTTIES" , RB, 96, true));
//        playerCardInputList.add(new CardInput(54033,  "ETO'O SS" , LW, 96, true));
        playerCardInputList.add(new CardInput(54281,  "GREALISH PREMIUM FUTTIES" , LW, 96, true));
        playerCardInputList.add(new CardInput(54225,  "CLAUSS PREMIUM FUTTIES" , RWB, 96, true));

        playerCardInputList.add(new CardInput(53214,  "KANE TOTS" , ST, 95));
        playerCardInputList.add(new CardInput(54174,  "CAHILL FUTTIES" , ST, 95));
        playerCardInputList.add(new CardInput(54070,  "MAGUIRE SS" , ST, 95, true));
        playerCardInputList.add(new CardInput(54009,  "RIJKAARD SS" , ST, 95, true));
        playerCardInputList.add(new CardInput(54257,  "FALCAO PREMIUM FUTTIES" , ST, 95, true));
        playerCardInputList.add(new CardInput(52956,  "VAN BASTEN TITAN", ST, 95, true));
//        playerCardInputList.add(new CardInput(54062,  "LUIS FIGO SS", ST, 95, true));
        playerCardInputList.add(new CardInput(53182,  "SANCHEZ TOTS", ST, 95, true));
//        playerCardInputList.add(new CardInput(54194,  "FORLAN FUTTIES", ST, 95, true));
        playerCardInputList.add(new CardInput(54000,  "MAHREZ SS", ST, 95, true));
//        playerCardInputList.add(new CardInput(53933,  "SERGIO BUSQUETS EOE" , CDM, 95));
//        playerCardInputList.add(new CardInput(54036,  "SEEDORF SS" , CDM, 95, true));
        playerCardInputList.add(new CardInput(54266,  "MASCHERANO FUTTIES" , CDM, 95, true));
//        playerCardInputList.add(new CardInput(54075,  "ZOLA SS" , CAM, 95));
        playerCardInputList.add(new CardInput(54177,  "SHAQIRI PREMIUM FUTTIES" , CAM, 95));
//        playerCardInputList.add(new CardInput(54035,  "PETIT SS" , CAM, 95, true));
//        playerCardInputList.add(new CardInput(52909,  "DEL PIERO TT" , CF, 95));
//        playerCardInputList.add(new CardInput(53749,  "NKUNKU TOTS" , CF, 95));
//        playerCardInputList.add(new CardInput(53989,  "JORDI ALBA EOE" , LB, 95));
//        playerCardInputList.add(new CardInput(54071,  "KLOSTERMANN SS" , LB, 95));
        playerCardInputList.add(new CardInput(54215,  "CAPDEVILA FUTTIES" , LB, 95));
        playerCardInputList.add(new CardInput(53829,  "MARQUINHOS TOTS" , CB, 95, true));
//        playerCardInputList.add(new CardInput(54034,  "PETIT SS" , CB, 95, true));
//        playerCardInputList.add(new CardInput(53784,  "EDER MILITAO TOTS" , CB, 95, true));
//        playerCardInputList.add(new CardInput(54213,  "DIEGO CARLOS FUTTIES" , CB, 95, true));
//        playerCardInputList.add(new CardInput(54224,  "SCHOLES CS ICON" , CM, 95, true));
//        playerCardInputList.add(new CardInput(54248,  "TIMBER PREMIUM FUTTIES" , CM, 95));
//        playerCardInputList.add(new CardInput(53876,  "BARELLA TOTS" , CM, 95));
//        playerCardInputList.add(new CardInput(54008,  "SOCRATES SS" , CM, 95, true));
//        playerCardInputList.add(new CardInput(54061,  "LUIS FIGO SS" , CM, 95, true));
//        playerCardInputList.add(new CardInput(53785,  "PEDRI TOTS" , CM, 95, true));
//        playerCardInputList.add(new CardInput(54205,  "RUBEN NEVES PREMIUM FUTTIES" , CM, 95, true));
//        playerCardInputList.add(new CardInput(54172,  "BENNACER FUTTIES" , CM, 95, true));
        playerCardInputList.add(new CardInput(54239,  "PARK JI SUNG FUTTIES" , CM, 95, true));
//        playerCardInputList.add(new CardInput(54243,  "NANI PREMIUM FUTTIES" , LM, 95));
//        playerCardInputList.add(new CardInput(54236,  "GAKPO FUTTIES" , LW, 95));
//        playerCardInputList.add(new CardInput(54187,  "INSIGNE PREMIUM FUTTIES" , LW, 95, true));
//        playerCardInputList.add(new CardInput(54162,  "KENT PREMIUM FUTTIES" , RW, 95));
//        playerCardInputList.add(new CardInput(54191,  "DUMFRIES FUTTIES" , RW, 95, true));
        playerCardInputList.add(new CardInput(53935,  "JOTA TOTS" , RW, 95, true));
        playerCardInputList.add(new CardInput(54227,  "SIMONS PREMIUM FUTTIES" , RW, 95, true));

        playerCardInputList.add(new CardInput(53788,  "TER STEGEN TOTS", GK, 94, true));
//        playerCardInputList.add(new CardInput(53788,  "TER STEGEN UTOTS", GK, 94));
        playerCardInputList.add(new CardInput(54246,  "SAVIN PREMIUM FUTTIES", GK, 94, true));
//        playerCardInputList.add(new CardInput(54080,  "WALKER SS", GK, 94, true));
//        playerCardInputList.add(new CardInput(53215,  "CASEMIRO TOTS", CDM, 94, true));
//        playerCardInputList.add(new CardInput(54230,  "DELANEY PREMIUM FUTTIES", CDM, 94));
        playerCardInputList.add(new CardInput(54001,  "BAILLY SS", CDM, 94, true));
//        playerCardInputList.add(new CardInput(54025,  "VITINHA SS", ST, 94));
//        playerCardInputList.add(new CardInput(54048,  "CECH SS", ST, 94));
//        playerCardInputList.add(new CardInput(54106,  "CAVANI LU", ST, 94));
//        playerCardInputList.add(new CardInput(54140,  "JIMENEZ LU (2)" , ST, 94, true));
//        playerCardInputList.add(new CardInput(48429,  "LEWANDOWSKI OTW" , ST, 94));
//        playerCardInputList.add(new CardInput(53832,  "DAVID TOTS" , ST, 94, true));
//        playerCardInputList.add(new CardInput(52958,  "OWEN TT" , ST, 94, true));
//        playerCardInputList.add(new CardInput(53830,  "BEN YEDDER TOTS" , ST, 94, true));
//        playerCardInputList.add(new CardInput(54043,  "NEUER SS" , ST, 94, true));
//        playerCardInputList.add(new CardInput(52911,  "FERNANDO TORRES TT" , ST, 94, true));
//        playerCardInputList.add(new CardInput(54028,  "LINKS PREMIUM SS", LW, 94));
//        playerCardInputList.add(new CardInput(54229,  "KARLSSON PREMIUM FUTTIES", LW, 94));
//        playerCardInputList.add(new CardInput(53217,  "SON TOTSM", LW, 94, true));
//        playerCardInputList.add(new CardInput(53907,  "PEDRO GONCALVES TOTS", LW, 94, true));
//        playerCardInputList.add(new CardInput(54057,  "LUMEKA SS", CAM, 94, true));
//        playerCardInputList.add(new CardInput(54121,  "SAVANIER LU (2)", CAM, 94));
//        playerCardInputList.add(new CardInput(53258,  "BROWNHILL TOTS", CAM, 94, true));
//        playerCardInputList.add(new CardInput(53257,  "AKPOM TOTS", CAM, 94, true));
//        playerCardInputList.add(new CardInput(54086,  "ACUNA FLASH", CM, 94));
//        playerCardInputList.add(new CardInput(54102,  "CALHANOGLU LU", CM, 94));
//        playerCardInputList.add(new CardInput(53873,  "RABIOT TOTS", CM, 94, true));
        playerCardInputList.add(new CardInput(53833,  "VERRATTI TOTS", CM, 94, true));
//        playerCardInputList.add(new CardInput(54017,  "ZAMBROTTA SS", CM, 94));
//        playerCardInputList.add(new CardInput(52960,  "LAMPARD TT", CM, 94, true));
//        playerCardInputList.add(new CardInput(54169,  "GEDSON FERNANDES PREMIUM FUTTIES", CM, 94, true));
        playerCardInputList.add(new CardInput(54074,  "GOTZE PREMIUM SS", RW, 94));
//        playerCardInputList.add(new CardInput(53750,  "DIABY TOTS", RW, 94, true));
//        playerCardInputList.add(new CardInput(54044,  "RICHARLISON SS", RW, 94, true));
//        playerCardInputList.add(new CardInput(53991,  "BECKER PREMIUM SS" , CB, 94, true));
//        playerCardInputList.add(new CardInput(50599,  "EDER MILITAO TOTY" , CB, 94, true));
//        playerCardInputList.add(new CardInput(54228,  "ADERLLAN SANTOS PREMIUM FUTTIES" , CB, 94));
//        playerCardInputList.add(new CardInput(53884,  "SMALLING TOTS" , CB, 94, true));
//        playerCardInputList.add(new CardInput(53831,  "MEDINA TOTS" , CB, 94, true));
//        playerCardInputList.add(new CardInput(50625,  "NESTA TOTY" , CB, 94, true));
//        playerCardInputList.add(new CardInput(53230,  "VARANE TOTS" , CB, 94, true));
//        playerCardInputList.add(new CardInput(53805,  "MUKHTAR TOTS" , CF, 94));
        playerCardInputList.add(new CardInput(52910,  "BERGKAMP TT" , CF, 94));
//        playerCardInputList.add(new CardInput(52771,  "CANTONA BIRTHDAY" , CF, 94));
//        playerCardInputList.add(new CardInput(53990,  "FRANKOWSKI PREMIUM SS" , RM, 94,true));
//        playerCardInputList.add(new CardInput(54072,  "ROUSSILLON SS" , RB, 94, true));
//        playerCardInputList.add(new CardInput(54272,  "HEADLEY PREMIUM FUTTIES" , LWB, 94, true));
//        playerCardInputList.add(new CardInput(53870,  "HERNANDEZ TOTS" , LB, 94, true));

//        playerCardInputList.add(new CardInput(53835,  "SAMBA TOTS" , GK, 93));
//        playerCardInputList.add(new CardInput(53835,  "SAMBA CHAMP TOTS" , GK, 93,true));
        playerCardInputList.add(new CardInput(52914,  "CASILLAS TT" , GK, 93, true));
//        playerCardInputList.add(new CardInput(52835,  "KLUIVERT BIRTHDAY" , ST, 93));
//        playerCardInputList.add(new CardInput(54165,  "JOSELU MOMENTS" , ST, 93));
//        playerCardInputList.add(new CardInput(54208,  "INAKI WILLIAMS PREMIUM FUTTIES" , ST, 93,true));
        playerCardInputList.add(new CardInput(53909,  "TAREMI TOTS" , ST, 93, true));
//        playerCardInputList.add(new CardInput(53846,  "VALENCIA TOTS" , ST, 93,true));
//        playerCardInputList.add(new CardInput(50621,  "BALE EOE" , RW,93));
//        playerCardInputList.add(new CardInput(53219,  "SAKA TOTS" , RW,93,true));
//        playerCardInputList.add(new CardInput(52903,  "KEANE TITAN" , CM, 93));
//        playerCardInputList.add(new CardInput(53792,  "MERINO TOTS" , CM, 93,true));
//        playerCardInputList.add(new CardInput(53218,  "BRUNO GUIMARAES TOTS", CM, 93, true));
        playerCardInputList.add(new CardInput(53751,  "BRANDT TOTS", CM, 93,true));
//        playerCardInputList.add(new CardInput(54032,  "MILINKOVIC-SAVIC PREMIUM SS", CM, 93));
//        playerCardInputList.add(new CardInput(50613,  "PIRLO TOTY", CM, 93));
//        playerCardInputList.add(new CardInput(53880,  "BREMER TOTS", CB, 93, true));
//        playerCardInputList.add(new CardInput(54002,  "MITROVIC SS", CB, 93));
//        playerCardInputList.add(new CardInput(54027,  "SORLOTH SS", CB, 93));
        playerCardInputList.add(new CardInput(54047,  "GIROUD SS", CB, 93));
        playerCardInputList.add(new CardInput(54058,  "BUFFON PREMIUM SS", CB, 93));
//        playerCardInputList.add(new CardInput(54093,  "PACHO PREMIUM LU (2)", CB, 93));
//        playerCardInputList.add(new CardInput(54147,  "TIAGO DJALO LU (2)", CB, 93));
        playerCardInputList.add(new CardInput(54050,  "OCHOA PREMIUM SS", CB, 93));
//        playerCardInputList.add(new CardInput(52963,  "BLANC TT", CB, 93));
//        playerCardInputList.add(new CardInput(53789,  "KOUNDE TOTS", CB, 93));
//        playerCardInputList.add(new CardInput(53836,  "CLAUSS TOTS" , RWB, 93));
//        playerCardInputList.add(new CardInput(54073,  "GAVI SS" , RB, 93));
//        playerCardInputList.add(new CardInput(54038,  "ZAHA PREMIUM SS" , RB, 93));
//        playerCardInputList.add(new CardInput(52915,  "LAHM TT (2)" , RB, 93, true));
        playerCardInputList.add(new CardInput(54118,  "SILDILLIA LU (2)" , RB, 93));
        playerCardInputList.add(new CardInput(54078,  "BALLACK SS" , RB, 93, true));
//        playerCardInputList.add(new CardInput(50612,  "ZANETTI TOTY" , RB, 93, true));
//        playerCardInputList.add(new CardInput(54081,  "CAMAVINGA SS" , LB, 93));
//        playerCardInputList.add(new CardInput(54084,  "BOOTH PREMIUM SS" , LB, 93));
//        playerCardInputList.add(new CardInput(53793,  "BALDE TOTS" , LB, 93, true));
//        playerCardInputList.add(new CardInput(54160,  "CARVALHO MOMENTS" , CAM, 93));
//        playerCardInputList.add(new CardInput(54207,  "IVAN JAIME PREMIUM FUTTIES" , CAM, 93,true));
//        playerCardInputList.add(new CardInput(54220,  "ANTMAN PREMIUM FUTTIES" , CAM, 93,true));
//        playerCardInputList.add(new CardInput(53766,  "TALISCA TOTS" , CAM, 93, true));
//        playerCardInputList.add(new CardInput(53156,  "SIMONS TOTS" , CAM, 93, true));
//        playerCardInputList.add(new CardInput(53806,  "ALMADA TOTS" , CAM, 93));
//        playerCardInputList.add(new CardInput(54158,  "WITSEL LU (2)" , CDM, 93));
//        playerCardInputList.add(new CardInput(54192,  "RODRI FUTTIES" , CDM, 93));
//        playerCardInputList.add(new CardInput(54199,  "DANGER PREMIUM FUTTIES" , CDM, 93));
//        playerCardInputList.add(new CardInput(54221,  "SANGARE PREMIUM FUTTIES" , CDM, 93));
        playerCardInputList.add(new CardInput(54173,  "GOSENS FUTTIES" , LWB, 93));
//        playerCardInputList.add(new CardInput(53834,  "NUNO MENDES TOTS" , LWB, 93, true));
//        playerCardInputList.add(new CardInput(53220,  "GABRIEL MARTINELLI TOTS" , LW, 93));
//        playerCardInputList.add(new CardInput(53938,  "PELLEGRINO TOTS" , LW, 93));
//        playerCardInputList.add(new CardInput(53877,  "DI MARIA TOTSM" , CF, 93,true));
//        playerCardInputList.add(new CardInput(54065,  "PEPE PREMIUM SS" , CF, 93,true));
//        playerCardInputList.add(new CardInput(53186,  "COMAN TOTS" , LM, 93,true));
//        playerCardInputList.add(new CardInput(54077,  "BALLACK SS" , LM, 93,true));
        playerCardInputList.add(new CardInput(53802,  "LLORENTE TOTSM" , LM, 93,true));

//        playerCardInputList.add(new CardInput(50627,  "VAN DER SAR TOTY" , GK,92,true));
        playerCardInputList.add(new CardInput(53752,  "KOBEL TOTS" , GK,92,true));
//        playerCardInputList.add(new CardInput(52916,  "LAHM TITAN" , LB,92,true));
        playerCardInputList.add(new CardInput(53803,  "GALAN TOTSM" , LB, 92));
//        playerCardInputList.add(new CardInput(53226, "ZINCHENKO TOTS", LB, 92,true));
//        playerCardInputList.add(new CardInput(53949, "HECTOR EOE", LB, 92));
        playerCardInputList.add(new CardInput(53910, "GRIMALDO TOTS", LB, 92,true));
//        playerCardInputList.add(new CardInput(53174, "ROBERTSON TOTS", LB, 92,true));
        playerCardInputList.add(new CardInput(52917, "ROBERTO CARLOS TT", LB, 92,true));
//        playerCardInputList.add(new CardInput(54037, "RIQUELME SS", LB, 92,true));
//        playerCardInputList.add(new CardInput(53754, "DAVIES TOTS", LB, 92,true));
        playerCardInputList.add(new CardInput(53993, "TOKO EKAMBI PREMIUM SS", LB, 92,true));
        playerCardInputList.add(new CardInput(54010, "FERNANDO HIERRO SS", LB, 92,true));
//        playerCardInputList.add(new CardInput(53117, "ABRAHAM RTTF", ST, 92));
//        playerCardInputList.add(new CardInput(53867,  "LUKAKU TOTSM" , ST, 92));
//        playerCardInputList.add(new CardInput(53920,  "THIAGO SILVA SS" , ST, 92));
//        playerCardInputList.add(new CardInput(54046,  "PEPE REINA SS" , ST, 92));
//        playerCardInputList.add(new CardInput(54150,  "JIMENEZ LU" , ST, 92));
//        playerCardInputList.add(new CardInput(52516,  "ISAK FANT" , ST, 92,true));
//        playerCardInputList.add(new CardInput(50656,  "KANE TOTYHM" , ST, 92));
        playerCardInputList.add(new CardInput(53756,  "KOLO MUANI TOTS" , ST, 92,true));
//        playerCardInputList.add(new CardInput(52619,  "MORIENTES FANT" , ST, 92,true));
//        playerCardInputList.add(new CardInput(53755,  "FULLKRUG TOTS" , ST, 92,true));
        playerCardInputList.add(new CardInput(53755,  "ICARDI TOTS" , ST, 92,true));
//        playerCardInputList.add(new CardInput(52948,  "FORLAN TT" , ST, 92,true));
//        playerCardInputList.add(new CardInput(53261,  "JOAO PEDRO TOTS" , ST, 92,true));
        playerCardInputList.add(new CardInput(51228,  "ALVAREZ FS" , ST, 92,true));
//        playerCardInputList.add(new CardInput(53222, "TRIPPIER TOTS", RB, 92));
        playerCardInputList.add(new CardInput(54003, "ORSOLINI SS", RB, 92));
        playerCardInputList.add(new CardInput(53881, "DI LORENZO TOTS", RB, 92,true));
//        playerCardInputList.add(new CardInput(53795, "MOLINA TOTS", RB, 92,true));
        playerCardInputList.add(new CardInput(54011, "FERNANDO HIERRO SS", RB, 92,true));
//        playerCardInputList.add(new CardInput(53753, "FRIMPONG TOTS", RWB, 92));
//        playerCardInputList.add(new CardInput(53911, "JOAO MARIO TOTS", RM, 92,true));
        playerCardInputList.add(new CardInput(53260, "TELLA TOTS", RM, 92,true));
//        playerCardInputList.add(new CardInput(54095, "STERLING LU", RW, 92));
//        playerCardInputList.add(new CardInput(53807, "VELA TOTS", RW, 92,true));
//        playerCardInputList.add(new CardInput(53939, "GOODWIN TOTS", LM, 92,true));
//        playerCardInputList.add(new CardInput(54054, "TOLISSO SS", LM, 92,true));
//        playerCardInputList.add(new CardInput(53237,  "HAVERTZ FLASH" , CAM, 92));
//        playerCardInputList.add(new CardInput(54122,  "SAVANIER LU" , CAM, 92));
//        playerCardInputList.add(new CardInput(53205,  "MITOMA TOTS" , LW, 92));
        playerCardInputList.add(new CardInput(54064,  "CAMPBELL SS" , LW, 92,true));
//        playerCardInputList.add(new CardInput(53848,  "BORINI TOTS" , LW, 92,true));
//        playerCardInputList.add(new CardInput(53740,  "LAPORTE FLASH" , CB, 92));
//        playerCardInputList.add(new CardInput(52838,  "DESAILLY BIRTHDAY" , CB, 92));
//        playerCardInputList.add(new CardInput(53225,  "SALIBA TOTS" , CB, 92));
//        playerCardInputList.add(new CardInput(54178,  "FERRARI PREMIUM FUTTIES" , CB, 92));
//        playerCardInputList.add(new CardInput(53872,  "TOMORI TOTSM" , CB, 92,true));
//        playerCardInputList.add(new CardInput(52918,  "FERDINAND TT" , CB, 92,true));
//        playerCardInputList.add(new CardInput(53845,  "MAVIDIDI TOTSM" , LM, 92));
//        playerCardInputList.add(new CardInput(53843,  "SISSOKO TOTSM" , CDM, 92));
//        playerCardInputList.add(new CardInput(53794,  "GABRI VEIGA TOTSM" , CM, 92,true));
//        playerCardInputList.add(new CardInput(54082,  "DEMBELE SS" , CM, 92,true));
//        playerCardInputList.add(new CardInput(53932,  "MILNER EOE" , CM, 92));
//        playerCardInputList.add(new CardInput(54114,  "FERNANDEZ LU" , CM, 92));
//        playerCardInputList.add(new CardInput(53871,  "TONALI TOTS" , CM, 92));
//        playerCardInputList.add(new CardInput(53167,  "BENNACER TOTS" , CM, 92));
        playerCardInputList.add(new CardInput(54053,  "ADEYEMI SS" , CM, 92));
//        playerCardInputList.add(new CardInput(53837,  "FOFANA TOTS" , CM, 92));
//        playerCardInputList.add(new CardInput(53223,  "ODEGAARD TOTS" , CM, 92));
        playerCardInputList.add(new CardInput(53155,  "TADIC TOTS" , CF, 92,true));


        playerCardInputList.add(new CardInput(52751,  "EDERSON FUTB(2)" , GK,91));
//        playerCardInputList.add(new CardInput(64,  "VAN DER SAR" , GK,91));
        playerCardInputList.add(new CardInput(53263,  "VIGOUROUX TOTS" , GK,91));
//        playerCardInputList.add(new CardInput(54039,  "CABRERA PREMIUM SS" , GK,91));
        playerCardInputList.add(new CardInput(53145,  "REYNA TOTSM" , LM, 91));
        playerCardInputList.add(new CardInput(53757,  "SANE TOTS" , LM, 91,true));
//        playerCardInputList.add(new CardInput(52518,  "BENRAHMA FANT" , LM, 91));
//        playerCardInputList.add(new CardInput(26262,  "LEWANDOWSKI" , ST, 91));
        playerCardInputList.add(new CardInput(26263,  "MBAPPE" , ST, 91));
        playerCardInputList.add(new CardInput(53913,  "GONCALO RAMOS TOTS" , ST, 91,true));
        playerCardInputList.add(new CardInput(53264,  "GYOKERES TOTS" , ST, 91,true));
        playerCardInputList.add(new CardInput(50225,  "BUTRAGUENO WC" , ST, 91,true));
//        playerCardInputList.add(new CardInput(53206,  "PALHINHA TOTS" , CDM, 91));
//        playerCardInputList.add(new CardInput(53917,  "LOBOTKA TOTS" , CDM, 91));
//        playerCardInputList.add(new CardInput(54159,  "WITSEL LU" , CDM, 91));
//        playerCardInputList.add(new CardInput(52919,  "ESSIEN TT" , CDM, 91,true));
//        playerCardInputList.add(new CardInput(53777,  "GUERREIRO TOTS" , LB, 91));
        playerCardInputList.add(new CardInput(53994,  "HAZARD PREMIUM SS" , LB, 91));
        playerCardInputList.add(new CardInput(53764,  "LACROIX TOTSM" , CB, 91));
//        playerCardInputList.add(new CardInput(53838,  "TODIBO TOTS" , CB, 91,true));
//        playerCardInputList.add(new CardInput(52754,  "MARQUINHOS BIRTHDAY" , CB, 91));
        playerCardInputList.add(new CardInput(53912,  "OTAMENDI TOTS" , CB, 91,true));
        playerCardInputList.add(new CardInput(53149,  "GEERTRUIDA TOTS" , CB, 91,true));
        playerCardInputList.add(new CardInput(52902,  "LUCIO TT" , CB, 91,true));
//        playerCardInputList.add(new CardInput(53808,  "DRIUSSI TOTS" , CAM, 91,true));
        playerCardInputList.add(new CardInput(53804,  "FEKIR TOTSM" , CAM, 91));
        playerCardInputList.add(new CardInput(53839,  "CABELLA TOTS" , CAM, 91));
        playerCardInputList.add(new CardInput(53850,  "MERTENS TOTS " , CAM, 91));
//        playerCardInputList.add(new CardInput(52622, "KUYT FANT", CAM, 91));
//        playerCardInputList.add(new CardInput(54004, "ALVAREZ SS", CAM, 91));
        playerCardInputList.add(new CardInput(50184, "GOMEZ WCPTG", CAM, 91));
        playerCardInputList.add(new CardInput(53840,  "TRAORE TOTS" , RB, 91));
//        playerCardInputList.add(new CardInput(54119,  "SILDILLIA LU" , RB, 91));
//        playerCardInputList.add(new CardInput(53941,  "MUNOZ TOTS" , RB, 91));
//        playerCardInputList.add(new CardInput(26265,  "MESSI" , RW, 91));
//        playerCardInputList.add(new CardInput(51769, "LAMELA RTTF", RW, 91));
//        playerCardInputList.add(new CardInput(53908,  "HECTOR BELLERIN TOTSM" , RWB, 91));
//        playerCardInputList.add(new CardInput(51773,  "PHILLIPS RTTF" , CM,91));
//        playerCardInputList.add(new CardInput(223,  "VIEIRA" , CM,91));
//        playerCardInputList.add(new CardInput(53185,  "AKE TOTS" , CM,91));
//        playerCardInputList.add(new CardInput(26264,  "DE BRUYNE" , CM,91));
//        playerCardInputList.add(new CardInput(26261,  "BENZEMA" , CF,91));
//        playerCardInputList.add(new CardInput(53767,  "ROMARINHO TOTS" , CF,91,true));
//        playerCardInputList.add(new CardInput(51753,  "FIRMINO RTTF" , CF,91,true));
//        playerCardInputList.add(new CardInput(54157,  "TERRIER LU" , LW,91));
//        playerCardInputList.add(new CardInput(54066,  "EN-NESYRI PREMIUM SS" , LW,91));
        playerCardInputList.add(new CardInput(53154,  "BERGWIJN TOTS" , LW,91,true));
//        playerCardInputList.add(new CardInput(51765,  "CHIESA RTTF" , LW,91,true));
        playerCardInputList.add(new CardInput(53882,  "CUADRADO TOTSM" , RM,91));

        playerCardInputList.add(new CardInput(26270,  "NEUER" , GK,90));
        playerCardInputList.add(new CardInput(26269,  "COURTOIS" , GK,90,true));
//        playerCardInputList.add(new CardInput(53170,  "DE GEA CHAMP TOTS" , GK,90));
//        playerCardInputList.add(new CardInput(52750,  "EDERSON FUTB(1)" , GK,90));
//        playerCardInputList.add(new CardInput(26266,  "SALAH" , RW,90));
//        playerCardInputList.add(new CardInput(53886,  "STREFEZZA TOTS" , RW,90,true));
//        playerCardInputList.add(new CardInput(53151,  "KUDUS TOTS" , RW,90,true));
//        playerCardInputList.add(new CardInput(132,  "STOICHKOV" , LW,90));
//        playerCardInputList.add(new CardInput(51669,  "KVARATSKHELIA FS" , LW,90,true));
//        playerCardInputList.add(new CardInput(52839,  "BARNES BIRTHDAY" , LW,90,true));
//        playerCardInputList.add(new CardInput(26250,  "LUCIO" , CB,90));
//        playerCardInputList.add(new CardInput(52822,  "HUMMELS BIRTHDAY" , CB,90));
//        playerCardInputList.add(new CardInput(26267,  "VAN DIJK" , CB,90));
//        playerCardInputList.add(new CardInput(53761,  "DOEKHI TOTS" , CB,90,true));
        playerCardInputList.add(new CardInput(53760,  "SCHLOTTERBECK TOTS" , CB,90,true));
        playerCardInputList.add(new CardInput(53945,  "ARSENIC TOTS" , CB,90,true));
//        playerCardInputList.add(new CardInput(54149,  "TIAGO DJALO LU" , CB,90));
//        playerCardInputList.add(new CardInput(54117,  "PACHO LU" , CB,90));
//        playerCardInputList.add(new CardInput(52520,  "SKRINIAR FANT" , CB,90));
//        playerCardInputList.add(new CardInput(52610,  "UPAMECANO FANT" , CB,90));
//        playerCardInputList.add(new CardInput(52521,  "SALIBA FANT" , CB,90));
//        playerCardInputList.add(new CardInput(53801,  "DAVID GARCIA TOTS" , CB,90,true));
//        playerCardInputList.add(new CardInput(52719,  "GREALISH FUTB(2)" , CAM,90,true));
//        playerCardInputList.add(new CardInput(53245,  "DANI OLMO MOTM" , CAM,90));
//        playerCardInputList.add(new CardInput(53758,  "HOFMANN TOTS" , CAM,90));
//        playerCardInputList.add(new CardInput(52949,  "COLE TT" , CAM,90));
//        playerCardInputList.add(new CardInput(100,  "RIJKAARD" , CDM,90));
//        playerCardInputList.add(new CardInput(53147,  "CAICEDO TOTSM" , CDM, 90));
//        playerCardInputList.add(new CardInput(53841,  "ANDRE TOTS" , CDM, 90,true));
//        playerCardInputList.add(new CardInput(53256,  "CHONG TOTSM" , CM, 90));
//        playerCardInputList.add(new CardInput(50660,  "PEDRI TOTYHM" , CM, 90));
//        playerCardInputList.add(new CardInput(53267,  "BANNAN TOTS" , CM, 90,true));
//        playerCardInputList.add(new CardInput(53852,  "NDIAYE TOTS" , CM, 90,true));
//        playerCardInputList.add(new CardInput(51668,  "FERNANDEZ FS" , CM, 90,true));
//        playerCardInputList.add(new CardInput(53152,  "PAVLIDIS CHAMP TOTS" , ST, 90));
//        playerCardInputList.add(new CardInput(53759,  "THURAM TOTS" , ST, 90));
//        playerCardInputList.add(new CardInput(53791,  "CASTELLANOS TOTSM" , ST, 90));
//        playerCardInputList.add(new CardInput(53895,  "DZEKO MOTM" , ST, 90));
//        playerCardInputList.add(new CardInput(53769,  "IGHALO TOTS" , ST, 90,true));
//        playerCardInputList.add(new CardInput(51231,  "ADEYEMI FS" , ST, 90));
//        playerCardInputList.add(new CardInput(53943,  "MIKAUTADZE TOTS" , ST, 90));
//        playerCardInputList.add(new CardInput(50551,  "IBRAHIMOVIC FUTC" , ST, 90));
//        playerCardInputList.add(new CardInput(53266,  "GILES TOTS" , LB, 90,true));
//        playerCardInputList.add(new CardInput(50501,  "ALEXANDER-ARNOLD FUTC" , RB, 90));
//        playerCardInputList.add(new CardInput(32,  "CARLOS ALBERTO MID" , RB, 90));
//        playerCardInputList.add(new CardInput(53188,  "TAVERNIER TOTS" , RB, 90,true));
//        playerCardInputList.add(new CardInput(52612,  "MITOMA FANT" , LM, 90));
//        playerCardInputList.add(new CardInput(51230,  "MUDRYK FS" , LM, 90));

//        playerCardInputList.add(new CardInput(26276, "ALISSON" , GK,89));
//        playerCardInputList.add(new CardInput(26278, "EDERSON" , GK,89));
//        playerCardInputList.add(new CardInput(52758, "LAFONT BIRTHDAY" , GK,89));
//        playerCardInputList.add(new CardInput(26280, "OBLAK" , GK,89,true));
//        playerCardInputList.add(new CardInput(50396, "BUTLAND WW" , GK,89));
//        playerCardInputList.add(new CardInput(50663, "MAIGNAN TOTYHM" , GK,89));
//        playerCardInputList.add(new CardInput(52952, "DUDEK TT" , GK,89,true));
//        playerCardInputList.add(new CardInput(52880,  "MEUNIER SHOWDOWN" , RM,89));
//        playerCardInputList.add(new CardInput(52616,  "WIMMER FANT" , RM,89));
//        playerCardInputList.add(new CardInput(51672,  "TIMBER FS" , RB,89));
//        playerCardInputList.add(new CardInput(52927,  "DI LORENZO TOTW" , RB,89,true));
//        playerCardInputList.add(new CardInput(53853,  "KADIOGLU TOTS" , RB,89,true));
//        playerCardInputList.add(new CardInput(53947,  "LUCIONI TOTS" , RB,89,true));
//        playerCardInputList.add(new CardInput(51690,  "MALACIA FS" , LWB,89));
//        playerCardInputList.add(new CardInput(52523,  "ANGELINO FANT" , LWB,89));
//        playerCardInputList.add(new CardInput(52626,  "TAGLIAFICO FANT" , LB,89));
//        playerCardInputList.add(new CardInput(26273,  "MANE" , LW,89));
//        playerCardInputList.add(new CardInput(26271,  "NEYMAR JR" , LW,89));
        playerCardInputList.add(new CardInput(26272,  "SON" , LW,89));
//        playerCardInputList.add(new CardInput(48485,  "FODEN RTTK" , LW,89));
//        playerCardInputList.add(new CardInput(52791,  "DANI OLMO TOTW" , RW,89));
//        playerCardInputList.add(new CardInput(53771,  "FOUZAIR TOTS" , RW,89,true));
//        playerCardInputList.add(new CardInput(50188,  "BRUNO GUIMARAES PTG" , CM,89));
//        playerCardInputList.add(new CardInput(53153,  "KOKCU TOTS" , CM,89));
//        playerCardInputList.add(new CardInput(53187,  "RICE TOTS" , CM, 89,true));
//        playerCardInputList.add(new CardInput(52627,  "RIQUI PUIG FANT" , CM, 89));
//        playerCardInputList.add(new CardInput(53189,  "THURAM TOTS" , CM, 89,true));
//        playerCardInputList.add(new CardInput(26242,  "BROLIN" , CAM,89));
//        playerCardInputList.add(new CardInput(52628,  "SZOBOSZLAI FANT" , CAM,89));
        playerCardInputList.add(new CardInput(26275,  "CASEMIRO" , CDM,89));
//        playerCardInputList.add(new CardInput(26274,  "KIMMICH" , CDM,89));
        playerCardInputList.add(new CardInput(26279,  "KANTE" , CDM,89,true));
        playerCardInputList.add(new CardInput(53946,  "ARTEAN TOTS" , CDM,89,true));
        playerCardInputList.add(new CardInput(53265,  "AHMEDHODZIC TOTS" , CB,89,true));
//        playerCardInputList.add(new CardInput(53283,  "JAGIELKA TOTSM" , CB, 89));
        playerCardInputList.add(new CardInput(53772,  "TOMBAKTI TOTS" , CB, 89,true));
//        playerCardInputList.add(new CardInput(53811,  "GLESNES TOTSM" , CB, 89));
//        playerCardInputList.add(new CardInput(53193,  "DANILO TOTS" , CB, 89));
//        playerCardInputList.add(new CardInput(53180,  "KIM MIN JAE TOTS" , CB, 89));
//        playerCardInputList.add(new CardInput(53207,  "WATKINS TOTS" , ST, 89));
//        playerCardInputList.add(new CardInput(26277,  "KANE" , ST, 89));
//        playerCardInputList.add(new CardInput(26252,  "MULLER" , ST, 89));
//        playerCardInputList.add(new CardInput(53270,  "CLARKE-HARRIS TOTS" , ST, 89));
//        playerCardInputList.add(new CardInput(50426,  "LACAZETTE WW" , ST, 89));
//        playerCardInputList.add(new CardInput(51671,  "NKETIAH FS" , ST, 89));
//        playerCardInputList.add(new CardInput(52826,  "WERNER BIRTHDAY" , ST, 89));
//        playerCardInputList.add(new CardInput(52827,  "EL SHAARAWY BIRTHDAY" , CF, 89));

        playerCardInputList.add(new CardInput(26571,  "NAVAS" , GK,88));
//        playerCardInputList.add(new CardInput(53774,  "MARCELO GROHE TOTS" , GK,88));
//        playerCardInputList.add(new CardInput(53812,  "BLAKE TOTS" , GK,88));
//        playerCardInputList.add(new CardInput(53812,  "BLAKE CHAMP TOTS" , GK,88));
//        playerCardInputList.add(new CardInput(26588,  "DONNARUMMA" , GK,88));
        playerCardInputList.add(new CardInput(26385,  "TER STEGEN" , GK,88));
//        playerCardInputList.add(new CardInput(51676,  "MESLIER FS" , GK,88));
        playerCardInputList.add(new CardInput(26282,  "KROOS" , CM,88,true));
//        playerCardInputList.add(new CardInput(51240,  "KUDUS FS" , CM,88));
//        playerCardInputList.add(new CardInput(52930,  "MILINKOVIC-SAVIC TOTW" , CM,88));
//        playerCardInputList.add(new CardInput(53243,  "BARELLA MOTM" , CM,88));
//        playerCardInputList.add(new CardInput(26386,  "MODRIC" , CM,88));
//        playerCardInputList.add(new CardInput(52782,  "KOKE BIRTHDAY 5S" , CM,88));
//        playerCardInputList.add(new CardInput(52780,  "KOKE BIRTHDAY 4S" , CM,88));
//        playerCardInputList.add(new CardInput(51673,  "FAGIOLI FS" , CM,88));
//        playerCardInputList.add(new CardInput(52718,  "GREALISH FUTB(1)" , CAM,88));
        playerCardInputList.add(new CardInput(52424,  "WEGHORST SHOWDOWN" , ST,88));
//        playerCardInputList.add(new CardInput(26281,  "HAALAND" , ST,88));
//        playerCardInputList.add(new CardInput(51664,  "OSIMHEN POTM" , ST,88));
//        playerCardInputList.add(new CardInput(52674,  "BAMFORD FUTB(2)" , ST,88));
//        playerCardInputList.add(new CardInput(52793,  "LUKAKU TOTW" , ST,88));
//        playerCardInputList.add(new CardInput(48589,  "DZEKO RULEBREAKERS" , ST,88));
//        playerCardInputList.add(new CardInput(52634,  "DAVID TOTW" , ST,88));
//        playerCardInputList.add(new CardInput(26233,  "SMOLAREK WCH" , ST,88));
//        playerCardInputList.add(new CardInput(215,  "MALDINI" , LB,88));
//        playerCardInputList.add(new CardInput(51852,  "JOAO CANCELO" , LB,88,true));
//        playerCardInputList.add(new CardInput(50506,  "JORDI ALBA FUTC" , LB,88));
//        playerCardInputList.add(new CardInput(51770,  "MIRANDA RTTF" , LB,88));
//        playerCardInputList.add(new CardInput(48475,  "SULE RTTK" , CB,88));
//        playerCardInputList.add(new CardInput(53197,  "CARTER-VICKERS TOTSM" , CB,88,true));
//        playerCardInputList.add(new CardInput(53272,  "PIERGIANNI TOTS" , CB,88));
//        playerCardInputList.add(new CardInput(53855,  "BARDAKCI CHAMP TOTS" , CB,88));
//        playerCardInputList.add(new CardInput(52662,  "MCTOMINAY STORY" , CDM,88));
//        playerCardInputList.add(new CardInput(27795,  "OKOCHA" , CAM, 88));
        playerCardInputList.add(new CardInput(26303,  "BERNARDO SILVA" , CAM, 88));
        playerCardInputList.add(new CardInput(26305,  "RUBEN DIAS" , CB,88));
//        playerCardInputList.add(new CardInput(53896,  "ACERBI MOTM" , CB,88));
//        playerCardInputList.add(new CardInput(26283,  "MARQUINHOS" , CB,88));
//        playerCardInputList.add(new CardInput(54021,  "NKUNKU MOTM" , CF,88));
//        playerCardInputList.add(new CardInput(54019,  "BOWEN MOTM" , RM,88));
//        playerCardInputList.add(new CardInput(53274,  "HOSKINS CHAMP TOTS" , LM,88));
//        playerCardInputList.add(new CardInput(54018,  "GALENO MOTM" , LM,88));
//        playerCardInputList.add(new CardInput(48691,  "HERNANDEZ OOP" , LW,88));
//        playerCardInputList.add(new CardInput(48692,  "JAMES OOP" , RW,88));
//        playerCardInputList.add(new CardInput(51757,  "LUCAS MOURA RTTF" , RW,88));
//        playerCardInputList.add(new CardInput(52759,  "EMERSON BIRTHDAY" , RWB,88));

//        playerCardInputList.add(new CardInput(53250,  "RYAN MOTM" , GK,87));
        playerCardInputList.add(new CardInput(26306,  "DE GEA" , GK,87,true));
        playerCardInputList.add(new CardInput(26308,  "HUGO LLORIS" , GK,87));
        playerCardInputList.add(new CardInput(26593,  "MAIGNAN" , GK,87,true));
//        playerCardInputList.add(new CardInput(51243,  "DIOGO COSTA FS" , GK,87));
//        playerCardInputList.add(new CardInput(50348,  "PAVARD STORY" , RB,87));
//        playerCardInputList.add(new CardInput(52526,  "TRIMMEL FANT" , RWB,87));
        playerCardInputList.add(new CardInput(26309,  "ALEXANDER-ARNOLD" , RB,87,true));
//        playerCardInputList.add(new CardInput(26312,  "ROBERTSON" , LB,87));
//        playerCardInputList.add(new CardInput(26417,  "GORETZKA" , CM,87));
//        playerCardInputList.add(new CardInput(26383,  "DE JONG" , CM,87));
//        playerCardInputList.add(new CardInput(51678,  "VINICIUS SOUZA FS" , CDM,87));
//        playerCardInputList.add(new CardInput(26570,  "VERRATI" , CM,87));
//        playerCardInputList.add(new CardInput(51677,  "WILLOCK FS" , CM,87));
//        playerCardInputList.add(new CardInput(52762,  "CHUKWUEZE BIRTHDAY" , RW,87));
//        playerCardInputList.add(new CardInput(52931,  "BERGHUIS TOTW" , RW,87));
//        playerCardInputList.add(new CardInput(51777,  "FELIPE ANDERSON RTTF" , RW,87));
        playerCardInputList.add(new CardInput(26415,  "MULLER" , CAM,87,true));
//        playerCardInputList.add(new CardInput(50399,  "CHIELLINI WW" , CAM,87));
//        playerCardInputList.add(new CardInput(52864,  "PESSINA BIRTHDAY 5S" , CAM,87));
        playerCardInputList.add(new CardInput(26311,  "RODRI" , CDM,87,true));
        playerCardInputList.add(new CardInput(26313,  "FABINHO" , CDM,87,true));
//        playerCardInputList.add(new CardInput(48591,  "PHILLIPS RULEBREAKERS" , CDM,87));
//        playerCardInputList.add(new CardInput(52761,  "ALESSANDRINI BIRTHDAY" , ST,87));
//        playerCardInputList.add(new CardInput(53,  "BERGKAMP" , ST,87));
//        playerCardInputList.add(new CardInput(53241,  "HLOZEK MOTM" , ST,87));
//        playerCardInputList.add(new CardInput(52641,  "OPENDA TOTW" , ST,87,true));
//        playerCardInputList.add(new CardInput(50517,  "QUAGLIARELLA FUTC" , ST,87));
//        playerCardInputList.add(new CardInput(51250,  "SANCET FS" , ST,87));
//        playerCardInputList.add(new CardInput(51759,  "MALEN RTTF" , ST,87));
//        playerCardInputList.add(new CardInput(51767,  "VOLLAND RTTF" , ST,87));
//        playerCardInputList.add(new CardInput(26384,  "RUDIGER" , CB,87));
//        playerCardInputList.add(new CardInput(50557,  "AZPILICUETA FUTC" , CB,
//        playerCardInputList.add(new CardInput(48653,  "SANCHEZ RULEBREAKERS" , CB,87));
//        playerCardInputList.add(new CardInput(50459,  "WEGHORST WW" , CB,87));
//        playerCardInputList.add(new CardInput(51242,  "KALULU FS" , CB,87));
//        playerCardInputList.add(new CardInput(52831,  "KJAER BIRTHDAY" , CB,87));
        playerCardInputList.add(new CardInput(26310,  "KOULIBALY" , CB,87));
//        playerCardInputList.add(new CardInput(50508,  "REBIC FUTC" , LW,87));

        playerCardInputList.add(new CardInput(26304,  "MENDY" , GK,86,true));
//        playerCardInputList.add(new CardInput(26421,  "TRAPP" , GK,86,true));
//        playerCardInputList.add(new CardInput(26358,  "SZCZESNY" , GK,86,true));
//        playerCardInputList.add(new CardInput(52765,  "LINGARD BIRTHDAY" , RW,86));
//        playerCardInputList.add(new CardInput(53892,  "GONZALEZ MOTM" , RW,86));
//        playerCardInputList.add(new CardInput(26499,  "MAHREZ" , RW,86));
//        playerCardInputList.add(new CardInput(48487,  "RAPHINHA RTTK" , RW,86));
//        playerCardInputList.add(new CardInput(48491,  "IKONE RTTK" , RW,86));
//        playerCardInputList.add(new CardInput(26717,  "DYBALA" , CF,86));
//        playerCardInputList.add(new CardInput(26424,  "NKUNKU" , CF,86));
        playerCardInputList.add(new CardInput(26302,  "LAPORTE" , CB,86));
        playerCardInputList.add(new CardInput(26339,  "THIAGO SILVA" , CB,86,true));
//        playerCardInputList.add(new CardInput(26381,  "ALABA" , CB,86,true));
//        playerCardInputList.add(new CardInput(26608,  "SKRINIAR" , CB,86,true));
//        playerCardInputList.add(new CardInput(50511,  "BASTONI FUTC" , CB,86));
//        playerCardInputList.add(new CardInput(52763,  "YERAY BIRTHDAY" , CB,86));
//        playerCardInputList.add(new CardInput(50475,  "HAHN WW" , ST,86));
//        playerCardInputList.add(new CardInput(26598,  "IMMOBILE" , ST,86,true));
        playerCardInputList.add(new CardInput(26601,  "LUKAKU" , ST,86));
//        playerCardInputList.add(new CardInput(50462,  "ADAMA TRAORE WW" , ST,86));
//        playerCardInputList.add(new CardInput(26595,  "MARTINEZ" , ST,86));
//        playerCardInputList.add(new CardInput(50566,  "COLEMAN FUTC" , RB,86));
//        playerCardInputList.add(new CardInput(52870,  "FERNANDEZ FOUND" , RB,86));
//        playerCardInputList.add(new CardInput(50405,  "TOLJAN WW" , RB,86));
////        playerCardInputList.add(new CardInput(53903,  "SALENG MOTM" , RM,86));
//        playerCardInputList.add(new CardInput(48601,  "BAILEY RULEBREAKERS" , RM,86));
//        playerCardInputList.add(new CardInput(51679,  "PLATA FS" , RM,86));
//        playerCardInputList.add(new CardInput(26382,  "PAREJO" , CM,86));
//        playerCardInputList.add(new CardInput(26603,  "MILINKOVIC-SAVIC" , CM,86));
        playerCardInputList.add(new CardInput(26349,  "THIAGO" , CM,86,true));
//        playerCardInputList.add(new CardInput(26604,  "BARELLA" , CM,86));
//        playerCardInputList.add(new CardInput(52764,  "SOW BIRTHDAY" , CM,86));
//        playerCardInputList.add(new CardInput(26607,  "BROZOVIC" , CDM,86));
//        playerCardInputList.add(new CardInput(48642,  "SISSOKO RULEBREAKERS" , CDM,86));
//        playerCardInputList.add(new CardInput(48704,  "TRAORE OOP" , CDM,86));
//        playerCardInputList.add(new CardInput(26728,  "BRUNO FERNANDES" , CAM,86));
        playerCardInputList.add(new CardInput(26419,  "COMAN" , LM,86));
//        playerCardInputList.add(new CardInput(48482,  "SIMON RTTK" , LM,86));
//        playerCardInputList.add(new CardInput(48641,  "SMITH ROWE RULEBREAKERS" , LM,86));
//        playerCardInputList.add(new CardInput(48481,  "TERRIER RTTK" , LW,86));
//        playerCardInputList.add(new CardInput(50402,  "KLUIVERT WW" , LW,86));
        playerCardInputList.add(new CardInput(26340,  "STERLING" , LW,86));
        playerCardInputList.add(new CardInput(26295,  "VINICIUS JR" , LW,86));
//        playerCardInputList.add(new CardInput(50560,  "BIRAGHI FUTC" , LB,86));
//        playerCardInputList.add(new CardInput(50562,  "GUNTER FUTC" , LB,86));
//        playerCardInputList.add(new CardInput(52862,  "MAEHLE BIRTHDAY 5S" , RWB,86));
//        playerCardInputList.add(new CardInput(52865,  "MAEHLE BIRTHDAY 4S" , RWB,86));
//        playerCardInputList.add(new CardInput(51245,  "SPENCE FS" , RWB,86));
//        playerCardInputList.add(new CardInput(51244,  "SINGO FS" , RWB,86));

        playerCardInputList.add(new CardInput(51285,  "SOMMER" , GK,85,true));
        playerCardInputList.add(new CardInput(26423,  "GULACSI" , GK,85,true));
//        playerCardInputList.add(new CardInput(50311,  "KEHRER WC PHENOM" , CB,85));
//        playerCardInputList.add(new CardInput(52769,  "MALDINI OOP" , CB,85));
        playerCardInputList.add(new CardInput(26425,  "DE LIGT" , CB,85));
//        playerCardInputList.add(new CardInput(52798,  "KONATE TOTW" , CB,85));
        playerCardInputList.add(new CardInput(26427,  "SULE" , CB,85,true));
//        playerCardInputList.add(new CardInput(48645,  "LACROIX RULEBREAKERS" , CB,85,true));
//        playerCardInputList.add(new CardInput(50519,  "HASEBE FUTC" , CB,85));
//        playerCardInputList.add(new CardInput(51776,  "TUTA RTTF" , CB,85,true));
//        playerCardInputList.add(new CardInput(48777,  "BUCHANAN DD" , RW,85));
//        playerCardInputList.add(new CardInput(48751,  "LEE DONG JUN DD" , RW,85));
//        playerCardInputList.add(new CardInput(50567,  "RAFA FUTC" , RW,85,true));
//        playerCardInputList.add(new CardInput(50564,  "SAELEMAEKERS FUTC" , RW,85,true));
//        playerCardInputList.add(new CardInput(52673,  "ABDULHAMID FOUND" , RB,85));
//        playerCardInputList.add(new CardInput(26756,  "WALKER" , RB,85,true));
//        playerCardInputList.add(new CardInput(26377,  "FEKIR" , CAM,85,true));
//        playerCardInputList.add(new CardInput(52766,  "GREGORE BIRTHDAY" , CAM,85));
//        playerCardInputList.add(new CardInput(26429,  "REUS" , CAM,85,true));
//        playerCardInputList.add(new CardInput(50515,  "NEUHAUS FUTC" , CAM,85));
//        playerCardInputList.add(new CardInput(52675,  "BAMFORD FUTB(1)" , ST,85));
//        playerCardInputList.add(new CardInput(52732,  "HALLER TOTW" , ST,85));
        playerCardInputList.add(new CardInput(52732,  "GERARD MORENO" , ST,85,true));
        playerCardInputList.add(new CardInput(26758,  "AUBAMEYANG" , ST,85,true));
        playerCardInputList.add(new CardInput(26379,  "IAGO ASPAS" , ST,85,true));
        playerCardInputList.add(new CardInput(26757,  "VARDY" , ST,85));
//        playerCardInputList.add(new CardInput(53249,  "JANSSEN MOTM" , ST,85));
        playerCardInputList.add(new CardInput(26428,  "SCHICK" , ST,85));
//        playerCardInputList.add(new CardInput(50563,  "STUANI FUTC" , ST,85));
//        playerCardInputList.add(new CardInput(51682,  "TILLMAN FS" , ST,85));
//        playerCardInputList.add(new CardInput(51693,  "BURKARDT FS" , ST,85));
//        playerCardInputList.add(new CardInput(26380,  "SERGIO BUSQUETS" , CDM,85));
//        playerCardInputList.add(new CardInput(52659,  "LEIBOLD STORY" , LB,85));
//        playerCardInputList.add(new CardInput(26389,  "JORDI ALBA" , LB,85));
//        playerCardInputList.add(new CardInput(26600,  "HERNANDEZ" , LB,85));
        playerCardInputList.add(new CardInput(26374,  "ACUNA" , LB,85,true));
        playerCardInputList.add(new CardInput(26602,  "KOSTIC" , LW,85));
//        playerCardInputList.add(new CardInput(53902,  "DIOGO GONCALVES MOTM" , LW,85));
//        playerCardInputList.add(new CardInput(26645,  "FODEN" , LW,85,true));
//        playerCardInputList.add(new CardInput(48445,  "BERGWIJN OTW" , LW,85));
        playerCardInputList.add(new CardInput(51840,  "JORGINHO" , CM,85,true));
//        playerCardInputList.add(new CardInput(26500,  "POGBA" , CM,85));
        playerCardInputList.add(new CardInput(26755,  "GUNDOGAN" , CM,85));
        playerCardInputList.add(new CardInput(26430,  "GNABRY" , CM,85));
        playerCardInputList.add(new CardInput(26297,  "PEDRI" , CM,85));
//        playerCardInputList.add(new CardInput(51274,  "DEPAY" , CF,85));
//        playerCardInputList.add(new CardInput(26350,  "DIOGO JOTA" , CF,85,true));

        playerCardInputList.add(new CardInput(26387,  "BOUNOU" , GK,84));
//        playerCardInputList.add(new CardInput(26418,  "CASTEELS" , GK,84));
        playerCardInputList.add(new CardInput(26776,  "HANDANOVIC" , GK,84,true));
//        playerCardInputList.add(new CardInput(26767,  "MARTINEZ" , GK,84));
//        playerCardInputList.add(new CardInput(26344,  "JAMES" , RWB,84));
//        playerCardInputList.add(new CardInput(26362,  "DI MARIA" , RW,84));
//        playerCardInputList.add(new CardInput(26299,  "DAVIES" , LB,84));
//        playerCardInputList.add(new CardInput(26760,  "OYARZABAL" , LW,84,true));
//        playerCardInputList.add(new CardInput(26634,  "INSIGNE" , LW,84));
//        playerCardInputList.add(new CardInput(26481,  "TADIC" , LW,84,true));
//        playerCardInputList.add(new CardInput(26502,  "SANCHO" , LW,84));
//        playerCardInputList.add(new CardInput(26352,  "DIAZ" , LW,84));
//        playerCardInputList.add(new CardInput(26432,  "HAZARD" , LW,84));
//        playerCardInputList.add(new CardInput(26296, "GREALISH", LW, 84));
//        playerCardInputList.add(new CardInput(26366, "CHIESA", LW, 84,true));
//        playerCardInputList.add(new CardInput(26596, "RAFAEL LEAO", LW, 84));
//        playerCardInputList.add(new CardInput(26770,  "MUNIAIN" , LM,84));
//        playerCardInputList.add(new CardInput(26416,  "SANE" , LM,84));
//        playerCardInputList.add(new CardInput(26764,  "PERISIC" , LM,84,true));
//        playerCardInputList.add(new CardInput(50411,  "CHONG WW" , LM,84));
//        playerCardInputList.add(new CardInput(26766,  "PARTEY" , CDM,84));
//        playerCardInputList.add(new CardInput(26762,  "KESSIE" , CDM,84));
        playerCardInputList.add(new CardInput(26771,  "NDIDI" , CDM,84));
//        playerCardInputList.add(new CardInput(26759,  "RICE" , CDM,84));
//        playerCardInputList.add(new CardInput(26599,  "TONALI" , CDM,84));
//        playerCardInputList.add(new CardInput(26504,  "ODEGAARD" , CAM,84));
//        playerCardInputList.add(new CardInput(26342,  "MOUNT" , CAM,84));
//        playerCardInputList.add(new CardInput(26777,  "GOMEZ" , CAM,84));
//        playerCardInputList.add(new CardInput(26298,  "HAVERTZ" , CAM,84));
//        playerCardInputList.add(new CardInput(26605,  "PELLEGRINI" , CM,84));
//        playerCardInputList.add(new CardInput(26343,  "KOVACIC" , CM,84));
//        playerCardInputList.add(new CardInput(53107,  "KAMPL TOTW" , CM,84));
        playerCardInputList.add(new CardInput(26606,  "CALHANOGLU" , CM,84));
        playerCardInputList.add(new CardInput(26730,  "TIELEMANS" , CM,84));
//        playerCardInputList.add(new CardInput(26763,  "DE PAUL" , CM,84));
//        playerCardInputList.add(new CardInput(53897,  "BOVE MOTM" , CM,84));
//        playerCardInputList.add(new CardInput(26293,  "BELLINGHAM" , CM,84));
//        playerCardInputList.add(new CardInput(48698,  "SUSO OOP" , CM,84));
//        playerCardInputList.add(new CardInput(48595,  "HERRERA RULEBREAKERS" , CM,84));
//        playerCardInputList.add(new CardInput(26301, "VALVERDE", CM, 84));
//        playerCardInputList.add(new CardInput(26765,  "CANALES" , RM,84,true));
        playerCardInputList.add(new CardInput(26414,  "DIABY" , RM,84));
//        playerCardInputList.add(new CardInput(26772,  "BERARDI" , RM,84,true));
//        playerCardInputList.add(new CardInput(26769,  "VARANE" , CB,84));
//        playerCardInputList.add(new CardInput(26773,  "DE VRIJ" , CB,84));
//        playerCardInputList.add(new CardInput(26392,  "SAVIC" , CB,84));
        playerCardInputList.add(new CardInput(26609,  "BASTONI" , CB,84));
//        playerCardInputList.add(new CardInput(26632,  "CHIELLINI" , CB,84));
//        playerCardInputList.add(new CardInput(26422,  "HERNANDEZ" , CB,84));
//        playerCardInputList.add(new CardInput(26360,  "BONUCCI" , CB,84));
//        playerCardInputList.add(new CardInput(26420,  "HUMMELS" , CB,84));
//        playerCardInputList.add(new CardInput(26351,  "MATIP" , CB,84));
//        playerCardInputList.add(new CardInput(26574,  "SERGIO RAMOS" , CB,84));
//        playerCardInputList.add(new CardInput(48596,  "GODFREY RULEBREAKERS" , CB,84));
//        playerCardInputList.add(new CardInput(26373,  "KOUNDE" , CB,84));
//        playerCardInputList.add(new CardInput(26294,  "VLAHOVIC" , ST,84));
//        playerCardInputList.add(new CardInput(26775,  "DZEKO" , ST,84));
//        playerCardInputList.add(new CardInput(26577,  "BEN YEDDER" , ST,84));
//        playerCardInputList.add(new CardInput(26749,  "MERTENS" , CF,84));
//        playerCardInputList.add(new CardInput(51258,  "JOAO FELIX" , CF,84));
//        playerCardInputList.add(new CardInput(26391,  "CARVAJAL" , RB,84));
//        playerCardInputList.add(new CardInput(26774,  "TRIPPIER" , RB,84));
//        playerCardInputList.add(new CardInput(26572,  "HAKIMI" , RB,84));
//        playerCardInputList.add(new CardInput(48646,  "MEUNIER RULEBREAKERS" , RB,84));

        playerCardInputList.add(new CardInput(26388,  "UNAI SIMON" , GK,83));
//        playerCardInputList.add(new CardInput(26799,  "KOBEL" , GK,83));
        playerCardInputList.add(new CardInput(26796,  "BAUMANN" , GK,83));
        playerCardInputList.add(new CardInput(26801,  "HRADECKY" , GK,83));
        playerCardInputList.add(new CardInput(26578,  "SCHMEICHEL" , GK,83));
//        playerCardInputList.add(new CardInput(52580,  "BIZOT TOTW" , GK,83));
        playerCardInputList.add(new CardInput(26576,  "FABIAN" , CM,83));
//        playerCardInputList.add(new CardInput(26575,  "CARLOS SOLER" , CM,83));
//        playerCardInputList.add(new CardInput(26353,  "HENDERSON" , CM,83));
//        playerCardInputList.add(new CardInput(26782,  "LEMAR" , CM,83));
//        playerCardInputList.add(new CardInput(26538,  "RUBEN NEVES" , CM,83));
//        playerCardInputList.add(new CardInput(26778,  "MERINO" , CM,83));
//        playerCardInputList.add(new CardInput(26783,  "KOKE" , CM,83));
        playerCardInputList.add(new CardInput(26731,  "LUIS ALBERTO" , CM,83));
//        playerCardInputList.add(new CardInput(26729,  "DAVID SILVA" , CAM,83));
//        playerCardInputList.add(new CardInput(26784,  "ZIELINSKI" , CAM,83));
//        playerCardInputList.add(new CardInput(26789,  "ARAUJO" , CB,83));
//        playerCardInputList.add(new CardInput(26573,  "KIMPEMBE" , CB,83));
//        playerCardInputList.add(new CardInput(26394,  "PAU TORRES" , CB,83));
//        playerCardInputList.add(new CardInput(26793,  "DIEGO CARLOS" , CB,83));
//        playerCardInputList.add(new CardInput(26798,  "ROMERO" , CB,83));
//        playerCardInputList.add(new CardInput(26800,  "GIMENEZ" , CB,83));
        playerCardInputList.add(new CardInput(26785,  "STONES" , CB,83));
//        playerCardInputList.add(new CardInput(26361,  "BREMER" , CB,83));
//        playerCardInputList.add(new CardInput(26792,  "RICARDO PEREIRA" , RB,83));
//        playerCardInputList.add(new CardInput(26393,  "JESUS NAVAS" , RB,83));
//        playerCardInputList.add(new CardInput(26365,  "CUADRADO" , RB,83));
//        playerCardInputList.add(new CardInput(26791,  "HOJBJERG" , CDM,83));
//        playerCardInputList.add(new CardInput(26795,  "FERNANDO" , CDM,83));
//        playerCardInputList.add(new CardInput(26413,  "LAIMER" , CDM,83));
//        playerCardInputList.add(new CardInput(26354,  "FIRMINO" , CF,83));
//        playerCardInputList.add(new CardInput(26786,  "GABRIEL JESUS" , ST,83));
//        playerCardInputList.add(new CardInput(26781,  "GRIEZMANN" , ST,83));
//        playerCardInputList.add(new CardInput(26797,  "ZAPATA" , ST,83));
//        playerCardInputList.add(new CardInput(26788,  "OSIMHEN" , ST,83));
//        playerCardInputList.add(new CardInput(54024,  "NSAME MOTM" , ST,83));
//        playerCardInputList.add(new CardInput(26779,  "CORREA" , ST,83));
//        playerCardInputList.add(new CardInput(26437,  "ASENSIO" , RW,83));
//        playerCardInputList.add(new CardInput(26345,  "ZIYECH" , RW,83));
//        playerCardInputList.add(new CardInput(26507,  "DEMBELE" , RW,83));
//        playerCardInputList.add(new CardInput(26780,  "RAPHINHA" , RW,83));
//        playerCardInputList.add(new CardInput(26790,  "ANGELINO" , LWB,83));
//        playerCardInputList.add(new CardInput(50712,  "GAKPO" , LW,83));
//        playerCardInputList.add(new CardInput(48648,  "ESTUPINAN RULEBREAKERS" , LB,83));
//        playerCardInputList.add(new CardInput(26434,  "MENDY" , LB,83));

//        playerCardInputList.add(new CardInput(52550,  "TRUBIN MOTM" , GK,82));
        playerCardInputList.add(new CardInput(26581,  "LOPES" , GK,82));
//        playerCardInputList.add(new CardInput(26810,  "PICKFORD" , GK,82));
//        playerCardInputList.add(new CardInput(26835,  "FABIANSKI" , GK,82));
        playerCardInputList.add(new CardInput(26826,  "RUI PATRICIO" , GK,82));
        playerCardInputList.add(new CardInput(26808,  "ONANA" , GK,82));
        playerCardInputList.add(new CardInput(26841,  "DAVID SORIA" , GK,82));
        playerCardInputList.add(new CardInput(50732,  "RULLI" , GK,82));
        playerCardInputList.add(new CardInput(26834,  "ALEX REMIRO" , GK,82));
        playerCardInputList.add(new CardInput(26328,  "RAMSDALE" , GK,82));
//        playerCardInputList.add(new CardInput(26802,  "CAN" , CM,82));
        playerCardInputList.add(new CardInput(26727,  "ERIKSEN" , CM,82));
//        playerCardInputList.add(new CardInput(26822,  "RAKITIC" , CM,82));
        playerCardInputList.add(new CardInput(26804,  "SERGI DARDER" , CM,82));
        playerCardInputList.add(new CardInput(26438,  "TCHOUAMENI" , CM,82));
        playerCardInputList.add(new CardInput(26805,  "KONDOGBIA" , CM,82));
        playerCardInputList.add(new CardInput(26395,  "WIRTZ" , CAM,82));
//        playerCardInputList.add(new CardInput(26452,  "DANI OLMO" , CAM,82));
//        playerCardInputList.add(new CardInput(26831,  "MADDISON" , CAM,82));
        playerCardInputList.add(new CardInput(26510,  "LUCAS PAQUETA" , CAM,82));
        playerCardInputList.add(new CardInput(26580,  "PAYET" , CAM,82));
//        playerCardInputList.add(new CardInput(26512,  "COUTINHO" , CAM,82));
        playerCardInputList.add(new CardInput(26477,  "BERGHUIS" , CAM,82));
//        playerCardInputList.add(new CardInput(26842,  "BRANDT" , CAM,82));
        playerCardInputList.add(new CardInput(26355,  "NUNEZ" , ST,82));
//        playerCardInputList.add(new CardInput(26830,  "ABRAHAM" , ST,82));
//        playerCardInputList.add(new CardInput(26828,  "MURIEL" , ST,82));
//        playerCardInputList.add(new CardInput(26517,  "IBRAHIMOVIC" , ST,82));
        playerCardInputList.add(new CardInput(26370,  "ARNAUTOVIC" , ST,82));
//        playerCardInputList.add(new CardInput(51287,  "GONCALO GUEDES" , ST,82));
        playerCardInputList.add(new CardInput(26579,  "VOLLAND" , ST,82));
//        playerCardInputList.add(new CardInput(26846,  "GIROUD" , ST,82));
//        playerCardInputList.add(new CardInput(26541,  "JIMENEZ" , ST,82));
//        playerCardInputList.add(new CardInput(26450,  "ANDRE SILVA" , ST,82));
//        playerCardInputList.add(new CardInput(26839,  "HALLER" , ST,82));
//        playerCardInputList.add(new CardInput(26449,  "WERNER" , ST,82));
//        playerCardInputList.add(new CardInput(38377,  "KASANWIRJO STORY" , RB,82));
//        playerCardInputList.add(new CardInput(26817,  "MAZRAOUI" , RB,82));
//        playerCardInputList.add(new CardInput(26813,  "GRIMALDO" , LB,82));
//        playerCardInputList.add(new CardInput(26832,  "GAYA" , LB,82));
//        playerCardInputList.add(new CardInput(26812,  "YURI BERCHICHE" , LB,82));
//        playerCardInputList.add(new CardInput(26726,  "GUERREIRO" , LB,82));
//        playerCardInputList.add(new CardInput(26818,  "DIGNE" , LB,82));
//        playerCardInputList.add(new CardInput(52551,  "AHMEDHODZIC MOTM" , CB,82));
        playerCardInputList.add(new CardInput(26819,  "INIGO MARTINEZ" , CB,82));
//        playerCardInputList.add(new CardInput(26845,  "ARITZ ELUSTONDO" , CB,82));
//        playerCardInputList.add(new CardInput(26837,  "COATES" , CB,82));
        playerCardInputList.add(new CardInput(26844,  "TAH" , CB,82));
//        playerCardInputList.add(new CardInput(26840,  "KJAER" , CB,82));
//        playerCardInputList.add(new CardInput(26334,  "SCHLOTTERBECK" , CB,82));
//        playerCardInputList.add(new CardInput(26814,  "GABRIEL PAULISTA" , CB,82));
//        playerCardInputList.add(new CardInput(26440,  "NACHO FERNANDEZ" , CB,82));
        playerCardInputList.add(new CardInput(26843,  "CHRISTENSEN" , CB,82));
//        playerCardInputList.add(new CardInput(26453,  "ORBAN" , CB,82));
//        playerCardInputList.add(new CardInput(26347,  "AZPILICUETA" , CB,82));
//        playerCardInputList.add(new CardInput(26833,  "ALDERWEIRELD" , CB,82));
//        playerCardInputList.add(new CardInput(26838,  "ACERBI" , CB,82));
        playerCardInputList.add(new CardInput(26847,  "RAUL ALBIOL" , CB,82));
//        playerCardInputList.add(new CardInput(51256,  "GORDON FS" , LM,82));
//        playerCardInputList.add(new CardInput(51829,  "DANJUMA" , LM,82));
//        playerCardInputList.add(new CardInput(26396,  "SAKA" , RM,82));
//        playerCardInputList.add(new CardInput(53113,  "PELLEGRINO TOTW" , LW,82));
//        playerCardInputList.add(new CardInput(26824,  "FERRAN TORRES" , LW,82));
//        playerCardInputList.add(new CardInput(26292,  "PULISIC" , LW,82));
//        playerCardInputList.add(new CardInput(26511,  "ZAHA" , LW,82));
//        playerCardInputList.add(new CardInput(26809,  "GOSENS" , LWB,82));
//        playerCardInputList.add(new CardInput(26346,  "CHILWELL" , LWB,82));
//        playerCardInputList.add(new CardInput(26836,  "KRAMARIC" , CF,82));
//        playerCardInputList.add(new CardInput(26807,  "TALISCA" , CF,82));
//        playerCardInputList.add(new CardInput(50724,  "MALINOVSKYI" , CF,82));
//        playerCardInputList.add(new CardInput(26367,  "LOCATELLI" , CDM,82));
//        playerCardInputList.add(new CardInput(26806,  "BENNACER" , CDM,82));
//        playerCardInputList.add(new CardInput(26820,  "GUEYE" , CDM,82));
        playerCardInputList.add(new CardInput(26811,  "OTAVIO" , RM,82));
//        playerCardInputList.add(new CardInput(26823,  "RAFA" , RW,82));
//        playerCardInputList.add(new CardInput(26825,  "DUMFRIES" , RWB,82));
    }

    protected static void populateTactics() {
        int index = 0;
        tacticList.add(index++, new Tactic( "4-1-2-1-2(2)" , Arrays.asList(GK, RB, CB, CB, LB, CDM, CM, CM, CAM, ST, ST)));
        tacticList.add(index++, new Tactic( "4-1-3-2" , Arrays.asList(GK, RB, CB, CB, LB, CDM, RM, CM, LM, ST, ST)));
        tacticList.add(index++, new Tactic( "4-2-2-2" , Arrays.asList(GK, RB, CB, CB, LB, CDM, CDM, CAM, CAM, ST, ST)));
        tacticList.add(index++, new Tactic( "4-2-4" , Arrays.asList(GK, RB, CB, CB, LB, CM, CM, RW, LW, ST, ST)));
        tacticList.add(index++, new Tactic( "4-3-1-2" , Arrays.asList(GK, RB, CB, CB, LB, CM, CM, CM, CAM, ST, ST)));
        tacticList.add(index++, new Tactic( "4-4-2" , Arrays.asList(GK, RB, CB, CB, LB, RM, CM, CM, LM, ST, ST)));
        tacticList.add(index++, new Tactic( "5-2-1-2" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RWB ,  LWB ,  CM ,  CM ,  CAM ,  ST ,  ST )));
        tacticList.add(index++, new Tactic( "5-1-2-2" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RWB ,  LWB ,  CDM ,  CM ,  CM ,  ST ,  ST )));

//        tacticList.add(index++, new Tactic( "4-1-2-1-2" , Arrays.asList(GK, RB, CB, CB, LB, CDM, RM, LM, CAM, ST, ST)));
//        tacticList.add(index++, new Tactic( "4-4-2(2)" , Arrays.asList(GK, RB, CB, CB, LB, CDM, CDM, RM, LM, ST, ST)));
        tacticList.add(index++, new Tactic( "3-1-4-2" , Arrays.asList(GK, CB, CB, CB, CDM, RM, CM, CM,  LM ,  ST ,  ST )));
        tacticList.add(index++, new Tactic( "3-4-1-2" , Arrays.asList( GK ,  CB ,  CB ,  CB  ,  RM ,  CM ,  CM ,  LM ,  CAM ,  ST ,  ST )));
        tacticList.add(index++, new Tactic( "3-5-2" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  CDM ,  CDM ,  RM ,  LM ,  CAM ,  ST ,  ST )));
//        tacticList.add(index++, new Tactic( "4-1-4-1" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  RM ,  CM ,  CM ,  LM ,  ST )));
//        tacticList.add(index++, new Tactic( "4-2-3-1" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  CDM ,  CAM ,  CAM ,  CAM ,  ST )));
//        tacticList.add(index++, new Tactic( "4-2-3-1(2)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  CDM ,  RM ,  CAM ,  LM ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-2-1" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CM ,  CM ,  CM ,  CF ,  CF ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-3" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CM ,  CM ,  CM ,  RW ,  LW ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-3(2)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  CM ,  CM ,  RW ,  LW ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-3(3)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  CDM ,  CM ,  RW ,  LW ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-3(4)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CM ,  CM ,  CAM ,  RW ,  LW ,  ST )));
//        tacticList.add(index++, new Tactic( "4-3-3(5)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  CDM ,  CM ,  CM ,  RW ,  LW ,  CF )));
//        tacticList.add(index++, new Tactic( "4-4-1-1" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  RM ,  CM ,  CM ,  LM ,  CF ,  ST )));
//        tacticList.add(index++, new Tactic( "4-4-1-1(2)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  RM ,  CM ,  CM ,  LM ,  CAM ,  ST )));
//        tacticList.add(index++, new Tactic( "4-5-1" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  RM ,  CM ,  LM ,  CAM ,  CAM ,  ST )));
//        tacticList.add(index++, new Tactic( "4-5-1(2)" , Arrays.asList( GK ,  RB ,  CB ,  CB ,  LB ,  RM ,  CM ,  CM ,  CM ,  LM ,  ST )));
//        tacticList.add(index++, new Tactic( "3-4-2-1" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RM ,  CM ,  CM ,  LM ,  CF ,  CF ,  ST )));
//        tacticList.add(index++, new Tactic( "3-4-3" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RM ,  CM ,  CM ,  LM ,  RW ,  ST ,  LW )));
//        tacticList.add(index++, new Tactic( "5-2-2-1" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RWB ,  LWB ,  CM ,  CM ,  RW ,  LW ,  ST )));
//        tacticList.add(index, new Tactic( "5-4-1" , Arrays.asList( GK ,  CB ,  CB ,  CB ,  RWB ,  LWB ,  RM ,  CM ,  CM ,  LM ,  ST )));
    }

    protected static void populatePositionMap() {
        positionAttributesMap.put(GK, List.of("gkreflexes", "gkhandling", "gkdiving","gkpositioning","gkkicking"));
        positionAttributesMap.put(RB, List.of("standingtackle", "marking", "slidingtackle","acceleration","longpassing"));
        positionAttributesMap.put(LB, List.of("standingtackle", "marking", "slidingtackle","acceleration","longpassing"));
        positionAttributesMap.put(CB, List.of("marking", "standingtackle", "strength","slidingtackle","aggression"));
        positionAttributesMap.put(RM, List.of("sprintspeed", "dribbling", "agility","shortpassing","reactions"));
        positionAttributesMap.put(LM, List.of("sprintspeed", "dribbling", "agility","shortpassing","reactions"));
        positionAttributesMap.put(CM, List.of("ballcontrol", "reactions", "vision","shortpassing","interceptions"));
        positionAttributesMap.put(ST, List.of("positioning", "finishing", "reactions","acceleration","strength"));
        positionAttributesMap.put(CDM, List.of("marking", "standingtackle", "interceptions","shortpassing","ballcontrol"));
        positionAttributesMap.put(CAM, List.of("dribbling", "agility", "vision","ballcontrol","sprintspeed"));
        positionAttributesMap.put(LWB, List.of("standingtackle", "marking", "aggression","crossing","sprintspeed"));
        positionAttributesMap.put(RWB, List.of("standingtackle", "marking", "aggression","crossing","sprintspeed"));
        positionAttributesMap.put(LW, List.of("dribbling", "agility", "sprintspeed","reactions","positioning"));
        positionAttributesMap.put(RW, List.of("dribbling", "agility", "sprintspeed","reactions","positioning"));
        positionAttributesMap.put(CF, List.of("positioning", "finishing", "dribbling","agility","longshotsaccuracy"));
    }

    protected static void populateManagers() {
        managerList.add(new Manager("A. CACIC", "Croatia", 317));
        managerList.add(new Manager("A. DIONISI", "Italy", 31));
        managerList.add(new Manager("A. POSTECOGLOU", "Australia", 50));
        managerList.add(new Manager("B. GAUL", "Germany",  66));
        managerList.add(new Manager("B. BERNER", "Switzerland",  189));
        managerList.add(new Manager("B. ROFOSSON", "Sweden",  16));
        managerList.add(new Manager("C. DEANMAN", "Canada",  31));
        managerList.add(new Manager("DIEGO MARTINEZ", "Spain",  53));
        managerList.add(new Manager("D. MOYES", "Scotland", 13));
        managerList.add(new Manager("EDER SARABIA", "Spain",  54));
        managerList.add(new Manager("E. TERZIC", "Croatia", 19));
        managerList.add(new Manager("E. BELOZOGLU", "Turkey", 68));
        managerList.add(new Manager("E. TEN HAG", "Netherlands", 13));
//        managerList.add(new Manager("E. BULUT", Country.TURKEY, 68));
//        managerList.add(new Manager("ETXEBERRIA", Country.SPAIN,  54));
        managerList.add(new Manager("F. KUDELKA", "Argentina",  1014));
        managerList.add(new Manager("F. TARALDRUD", "Norway",  31));
        managerList.add(new Manager("F. PECCHIA", "Italy",  32));
        managerList.add(new Manager("G. MILITO", "Argentina", 353));
//        managerList.add(new Manager("GAIZKA GARITANO", Country.SPAIN, 54));
        managerList.add(new Manager("H. STEFFEN", "Germany",  2076));
        managerList.add(new Manager("H. SOUMAHO'O", "Cameroon",  19));
        managerList.add(new Manager("H. VANHAEZEBROUCK", "Belgium",  4));
        managerList.add(new Manager("I. JURIC", "Croatia", 31));
        managerList.add(new Manager("J. GATFIELD", "Jamaica", 31));
        managerList.add(new Manager("J. THORUP", "Denmark",  1));
        managerList.add(new Manager("J. PERSSON", "Sweden",  56));
        managerList.add(new Manager("J. AGUIRRE", "Mexico",  53));
        managerList.add(new Manager("J. TRPISOVSKY", "Czech Republic", 319));
        managerList.add(new Manager("JUAN FERRANDO", "Spain",  2149));
//        managerList.add(new Manager("L. MADELON", Country.ARGENTINA,  353));
//        managerList.add(new Manager("L. GOTTI", "Italy",  31));
//        managerList.add(new Manager("L. PUSINERI", Country.ARGENTINA, 353));
//        managerList.add(new Manager("M. ALLEGRI", "Italy", 31));
        managerList.add(new Manager("M. PELLEGRINI","Chile",  53));
//        managerList.add(new Manager("M. BILEK", Country.CZECH, 319));
//        managerList.add(new Manager("MICHEL", Country.SPAIN, 53));
        managerList.add(new Manager("M. GALLARDO", "Argentina", 1003));
        managerList.add(new Manager("MARCO SILVA", "Portugal", 13));
        managerList.add(new Manager("M. VAN BOMMEL", "Netherlands", 4));
        managerList.add(new Manager("N. ESPIRINTO SANTO", "Portugal",  350));
        managerList.add(new Manager("M. LEKSIVIC", "Slovenia",  13));
//        managerList.add(new Manager("O. BURUK", Country.TURKEY, 68));
        managerList.add(new Manager("P. HOGMO", "Norway",  56));
//        managerList.add(new Manager("PACHETA", Country.SPAIN, 53));
        managerList.add(new Manager("PEDRO CAIXINHA", "Portugal", 1003));
        managerList.add(new Manager("PEP GUARDIOLA", "Spain", 13));
        managerList.add(new Manager("RUBEN AMORIM", "Portugal",  308));
        managerList.add(new Manager("R. LUCESCU", "Romania",  63));
        managerList.add(new Manager("R. ZADKOVICH", "Australia",  351));
//        managerList.add(new Manager("R. WICKY", Country.SWITZERLAND,  189));
//        managerList.add(new Manager("RUI PEDRO SILVA", Country.PORTUGAL, 308));
//        managerList.add(new Manager("S. BECCACECE", Country.ARGENTINA,  1014));
        managerList.add(new Manager("S. CHERCHESOV", "Russia",  2211));
        managerList.add(new Manager("S. COOPER", "Wales",  13));
//        managerList.add(new Manager("S. GONZALEZ", Country.SPAIN, 53));
        managerList.add(new Manager("T. TUCHEL", "Germany", 13));
        managerList.add(new Manager("VINCENTE MORENO", "Spain",  350));
//        managerList.add(new Manager("VASCO SEABRA", Country.PORTUGAL, 308));
        managerList.add(new Manager("V. WOLYNIEC", "Poland", 53));
    }

    protected static double getBodyTypeModifier(String bodyType) throws Exception {
        return switch (bodyType) {
            case "Unique" -> 99.00;
            case "Lean" -> 89.076;
            case "Average" -> 88.5;
            case "Stocky" -> 83.96;
            case "High & Average" -> 87.192;
            case "High & Average+" -> 88.4;
            case "High & Stocky" -> 82.712;
            case "Short & Lean" -> 81.4;
            case "Short & Lean-" -> 83.9;
            case "Short & Balanced" -> 80.816;
            case "Messi" -> 100.00;
            case "High & Lean" -> 80.536;
            case "Courtois" -> 100.00;
            case "Neymar" -> 100.00;
            case "Shaqiri" -> 90.00;
            case "CR7" -> 100.00;
            case "Ronaldinho" -> 100.00;
            case "Base R9" -> 100.00;
            case "R9" -> 100.00;
            case "Salah" -> 100.00;
            default -> throw new Exception("Invalid body type.");
        };
    }
}